"""new fields in user model

Revision ID: 0093395a6bcd
Revises: 55a0b9bb0652
Create Date: 2024-05-04 15:02:06.155943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0093395a6bcd'
down_revision = '55a0b9bb0652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
